# Generated by Django 2.2.11 on 2020-03-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_logs_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
